### ISSUE TITLE
TypeError: this._northEast is undefined when  loading geojson to map

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/suitability-analysis#14]
Hey Lawrence,

I started making a map page to view parcels - was hoping to show it in the morning, but passig on it for now. When trying to load the parcel layer's boundary, it shows "TypeError: this._northEast is undefined
...is._northEast.lng},getNorth:function(){return this._northEast.lat},contains:func..." and can't get the boundaries. This layer is loaded by leaflet-ajax, so it's possible that I'm misusing it. Could you look into this error and see if you can get the layer to display on the map nicely? Thanks!

**Comment by nickrsan** [comment]
Also, as a heads up, I moved the static files into a subfolder so that they're namespaced the way django recommends.

**Comment by nickrsan** [comment]
I think this is the solution: http://gis.stackexchange.com/a/178909/1955

**Comment by lilawren** [comment]
I reverted to the last stable commit ("Beginning of a webmap", 52a6771) and changed it to this:

`    <script language="JavaScript">
        var parcels = new L.geoJson.ajax("{% static "relocation/js/parcels.geojson" %}").addTo(parcel_map);
        parcels.on('layeradd', function (e) {
             parcel_map.fitBounds(parcels.getBounds());
        });
    </script>`

Which doesn't quite work because I've been getting 404 errors. Is parcels.geojson is actually created? I can't seem to find it among the static files.

**Comment by lilawren** [comment]
I created a basic polygon in http://geojson.io/#map=3/32.62/-99.32 and put the .geojson in the /static/relocation directory and it showed up using the code above.

**Comment by nickrsan** [comment]
I shaved 10 MB (about 2/7) of the size off of the parcels by reducing the coordinate precision in the export (see http://gdal.org/python/osgeo.ogr.DataSource-class.html#CopyLayer and http://www.gdal.org/drv_geojson.html for the difficult to find documentation on doing this). Changes in commit https://github.com/ucd-cws/suitability-analysis/commit/e793669d1caa35c310ec3ce5c3e9d2d6d3d180ac - if that's not enough to make this display properly, we can look into reducing the number of available fields or the length of field names, etc. In transit, gzipped, should only be 2.3MB, which is fine, but not sure how that'll be handled by browser on decompress.

**Comment by nickrsan** [comment]
New parcel exports shouldn't have this problem anymore once we view a location since it filters to the analysis area.
